FROM php:8.4-apache AS composer_builder

RUN apt-get update && apt-get install -y \
    build-essential \
    zip \
    unzip \
    curl \
    git \
    libzip-dev \
    libonig-dev \
    libssl-dev \
    pkg-config \
    librdkafka-dev \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && docker-php-ext-install mbstring zip \
    && pecl install mongodb \
    && pecl install rdkafka \
    && docker-php-ext-enable mongodb rdkafka \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

COPY composer.json composer.lock ./

RUN composer install --no-dev --optimize-autoloader --no-scripts

FROM php:8.4-apache AS production

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions rdkafka mongodb mbstring zip opentelemetry

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN a2enmod rewrite
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html

COPY --from=composer_builder /var/www/html/vendor /var/www/html/vendor

COPY . /var/www/html

RUN mkdir -p storage/framework/sessions \
             storage/framework/views \
             storage/framework/cache \
             bootstrap/cache \
    && chown -R www-data:www-data /var/www/html \
    && chmod -R 775 storage bootstrap/cache

# Clean up apt lists (Even though install-php-extensions does most of this)
RUN rm -rf /var/lib/apt/lists/*
